import React, { useState } from "react";
import { ArrowLeftRight, Cpu, Radio, Server, Code, Copy, Check } from "lucide-react";

export const Esp32MqttDiagram: React.FC = () => {
  const [deviceState, setDeviceState] = useState<"ON" | "OFF">("OFF");
  const [copied, setCopied] = useState(false);

  const sampleSketch = `// Auto-generated by Esp32CodeGenerator in com.soltini.app
#include <WiFi.h>
#include <PubSubClient.h>

const char* ssid = "Home_Network";
const char* password = "NETWORK_KEY";
const char* mqtt_server = "192.168.1.100";

WiFiClient espClient;
PubSubClient client(espClient);

const int RELAY_PIN = 16;
const char* topic_sub = "myra/devices/relay_01/set";
const char* topic_pub = "myra/devices/relay_01/state";

void callback(char* topic, byte* payload, unsigned int length) {
  payload[length] = '\\0';
  String msg = String((char*)payload);
  if (msg.indexOf("ON") >= 0) {
    digitalWrite(RELAY_PIN, HIGH);
    client.publish(topic_pub, "{\\"state\\":\\"ON\\"}");
  } else {
    digitalWrite(RELAY_PIN, LOW);
    client.publish(topic_pub, "{\\"state\\":\\"OFF\\"}");
  }
}

void setup() {
  pinMode(RELAY_PIN, OUTPUT);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sampleSketch);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full bg-neutral-900/50 border border-neutral-800 rounded-xl p-6 lg:p-8">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 pb-6 border-b border-neutral-800">
        <div>
          <h3 className="text-xl font-semibold text-neutral-100">
            MQTT Two-Way Synchronization & ESP32 Generator
          </h3>
          <p className="text-sm text-neutral-400 mt-1">
            How MqttManager, WifiMqttCredentialsStore, and Esp32CodeGenerator drive local hardware control.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setDeviceState(deviceState === "ON" ? "OFF" : "ON")}
            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
              deviceState === "ON"
                ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/50"
                : "bg-neutral-800 text-neutral-400 hover:text-neutral-200"
            }`}
          >
            Toggle Simulated Relay: {deviceState}
          </button>
        </div>
      </div>

      {/* Interactive 3-Node Architecture Flow */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-6">
        {/* Node 1: MYRA Android App */}
        <div className="bg-neutral-950 border border-neutral-800 rounded-lg p-5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-2 border-b border-neutral-850">
              <span className="text-xs font-mono text-cyan-400">01. Android Layer</span>
              <Cpu className="w-4 h-4 text-cyan-400" />
            </div>
            <h4 className="text-base font-semibold text-neutral-100 mt-2">
              MYRA Controller
            </h4>
            <div className="text-xs text-neutral-400 space-y-1.5 mt-2">
              <p>• DeviceController resolves voice intent</p>
              <p>• HomeDatabase (Room) stores device entities</p>
              <p>• WifiMqttCredentialsStore manages keys</p>
            </div>
          </div>
          <div className="mt-4 pt-3 border-t border-neutral-900 font-mono text-[11px] text-cyan-300">
            Payload: {"{"}"state": "{deviceState}"{"}"}
          </div>
        </div>

        {/* Node 2: MQTT Broker */}
        <div className="bg-neutral-950 border border-neutral-800 rounded-lg p-5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-2 border-b border-neutral-850">
              <span className="text-xs font-mono text-blue-400">02. Broker Bridge</span>
              <Server className="w-4 h-4 text-blue-400" />
            </div>
            <h4 className="text-base font-semibold text-neutral-100 mt-2">
              MQTT Broker (Mosquitto)
            </h4>
            <div className="text-xs text-neutral-400 space-y-1.5 mt-2">
              <p className="text-cyan-400 font-mono">PUB: myra/devices/relay_01/set</p>
              <p className="text-emerald-400 font-mono">SUB: myra/devices/relay_01/state</p>
              <p>• MqttManager auto-reconnects on loss</p>
            </div>
          </div>
          <div className="mt-4 pt-3 border-t border-neutral-900 font-mono text-[11px] text-neutral-400 flex items-center justify-between">
            <span>Protocol: MQTT 3.1.1</span>
            <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
          </div>
        </div>

        {/* Node 3: ESP32 Microcontroller */}
        <div className="bg-neutral-950 border border-neutral-800 rounded-lg p-5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-2 border-b border-neutral-850">
              <span className="text-xs font-mono text-emerald-400">03. Hardware Node</span>
              <Radio className="w-4 h-4 text-emerald-400" />
            </div>
            <h4 className="text-base font-semibold text-neutral-100 mt-2">
              ESP32 Microcontroller
            </h4>
            <div className="text-xs text-neutral-400 space-y-1.5 mt-2">
              <p>• Firmware generated by Esp32CodeGenerator</p>
              <p>• GPIO 16 triggers physical relay switch</p>
              <p>• Returns verified state packet</p>
            </div>
          </div>
          <div className="mt-4 pt-3 border-t border-neutral-900 font-mono text-[11px] flex items-center justify-between">
            <span className="text-neutral-400">Relay GPIO 16:</span>
            <span className={deviceState === "ON" ? "text-emerald-300 font-bold" : "text-neutral-500"}>
              {deviceState === "ON" ? "HIGH (Active)" : "LOW (Inactive)"}
            </span>
          </div>
        </div>
      </div>

      {/* Generated Code Sample Preview */}
      <div className="bg-neutral-950 border border-neutral-800 rounded-lg p-4 mt-4">
        <div className="flex items-center justify-between pb-3 border-b border-neutral-850">
          <div className="flex items-center gap-2">
            <Code className="w-4 h-4 text-cyan-400" />
            <span className="text-xs font-semibold text-neutral-200">
              Esp32CodeGenerator Output Sketch (Arduino C++)
            </span>
          </div>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 text-xs text-neutral-400 hover:text-neutral-200 transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Sketch</span>
              </>
            )}
          </button>
        </div>
        <pre className="text-xs text-neutral-300 font-mono p-3 bg-neutral-900/50 rounded overflow-x-auto max-h-52 mt-3">
          {sampleSketch}
        </pre>
      </div>
    </div>
  );
};
